// <auto-generated />
using System;
using AECademyHubServer.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AECademyHubServer.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231105020439_AddQueue")]
    partial class AddQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AECademyHubServer.Shared.Object.Object", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownloadNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reviews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("Objects");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("bc685571-7d85-42b3-90af-8f25afd827f3"),
                            AuthorGuid = new Guid("dc765a23-3913-44c2-aacb-0df49ce58385"),
                            Description = "A rhino facade model",
                            DownloadNumber = 1,
                            Name = "CW_Panel_A1001.3dm",
                            PermissionLevel = "Public",
                            PreviewUrl = "https://aecademyhub.blob.core.windows.net/aecademyhub/bc685571-7d85-42b3-90af-8f25afd827f3/CW_Panel_A1001.png",
                            Reviews = "Test Reviews",
                            Type = "Rhino",
                            Url = "https://aecademyhub.blob.core.windows.net/aecademyhub/bc685571-7d85-42b3-90af-8f25afd827f3/CW_Panel_A1001.3dm"
                        });
                });

            modelBuilder.Entity("AECademyHubServer.Shared.Queue.QueueRequest", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGuid");

                    b.ToTable("Queue");

                    b.HasData(
                        new
                        {
                            UserGuid = new Guid("f24be677-c15f-44d0-a110-d75181fba29e"),
                            ObjectGuid = new Guid("bc685571-7d85-42b3-90af-8f25afd827f3")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
